source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'SignatureTest' do
  pod 'YPDrawSignatureView', :path => '../'

    target 'SignatureTestTests' do
    end

end
